#!/bin/bash
FILE=gamecard
echo "Compiling & Executing with Valgrind:"
make $FILE
if test -f "./$FILE"; then
    valgrind --tool=memcheck --leak-check=yes --show-reachable=yes --num-callers=20 --log-file=a.out ./$FILE 
fi
echo "Finished executing with Valgrind."